### ISSUE TITLE
Clarify tag

### ISSUE THREAD

**Issue by arj03** [AljoschaMeyer/bamboo#3]
I remember being a bit confused the first time I read the spec that, under concepts and properties it says: a boolean that indicates whether this is a regular entry or an end-of-log marker.

But then later under encoding it is encoded as a tag using a byte, so it can contain multiple values.

**Comment by AljoschaMeyer** [comment]
Those are true statements. I'm not sure what the problem is :stuck_out_tongue:

It says "tag, either a zero byte (0x00) to indicate a regular log entry, or a one byte (0x01) to indicate an end-of-log marker", I can stick "No other values are allowed." at the end, would that have helped?

**Comment by arj03** [comment]
True :D

Yes that would help, maybe "No other values are allowed for now". I'm just thinking that it's great that it could easily be extended in the future if we found other good cases.

**Comment by arj03** [comment]
Excellent! Thanks @AljoschaMeyer
