### ISSUE TITLE
Ambiguity in description of verifying payloads

### ISSUE THREAD

**Issue by snej** [AljoschaMeyer/bamboo#7]
> Additionally, if the payload of an entry is available to a peer, the peer must check wether it hashes to the claimed (and signed) hash, and whether the size of the payload in bytes matches the claimed (and signed) size metadata. **If it doesn't, the feed must be considered invalid from that entry onwards** (there's zero tolerance for authors lying about payload sizes).

I realized while implementing this that there's a subtle ambiguity here. The bolded phrase applies only to a size mismatch, _not_ to a hash mismatch. If the hash doesn't match, the conclusion is that you received an incorrect or corrupted payload, not that the feed is lying. (Otherwise a malicious peer can make you reject valid feeds by sending you bogus payloads.) And of course the hash must be tested first.

To be precise:

```
if hash(payload) != entry.payload_hash
    return InvalidPayload  // This is not the correct payload
else if len(payload) != entry.size
    return InvalidEntry  // This entry lied about its payload size; reject it
else
    return ValidPayload  // This is the correct payload
```

**Comment by AljoschaMeyer** [comment]
You interpreted it in the intended way, but I can see how this part could be confusing. How about:

> Additionally, if the payload of an entry is available to a peer, the peer must check whether it hashes to the claimed (and signed) hash, and whether the size of the payload in bytes matches the claimed (and signed) size metadata. **If the claimed hash matches but the claimed size doesn't**, the feed must be considered invalid from that entry onward (there's zero tolerance for authors lying about payload sizes).

**Comment by snej** [comment]
Sounds good to me!
